### ISSUE TITLE
Byproducts not listed on recipe pages.

### ISSUE THREAD

**Issue by Soyweiser** [DanmakuDan/cdda-itembrowser#1]
Byproducts like, ""byproducts": [ [ "plant_fibre", 5 ] ]," from the making starch from cattail_rhizome (see json/recipes/recipe_food.json around line 2020). Are not listed on the item browser.

**Comment by DanmakuDan** [comment]
I got around to figuring out some of the model/view/controller setup in order to add the byproduct display. It should be visible on Chezzo's site now.
