### ISSUE TITLE
Some recipes do not appear in the "Recipes" tabs.

### ISSUE THREAD

**Issue by SkuliAdams** [DanmakuDan/cdda-itembrowser#26]
The biggest example that I have found is that when one looks at the entry for the Burnt Out Bionic, the browser says the item is used in 23 different recipes. However, only four item recipes are shown under the recipe tab. Another is for the minireactor. It is said to have one recipe using it, but under the recipe tab, nothing is shown.

**Comment by DanmakuDan** [comment]
I think the uncrafting/disassembly entries are being counted as recipes for that label. It would be clearer if there was a separate label for those. You can see under the "can be obtained" info that the amount of items there match the recipe amount.
