### ISSUE TITLE
Brewable items not listed as brewable.

### ISSUE THREAD

**Issue by Soyweiser** [DanmakuDan/cdda-itembrowser#3]
Per this change: https://github.com/CleverRaven/Cataclysm-DDA/pull/16117 several items have a new json value 'brewable' like this:

`        "brewable" : {
            "time" : 7200,
            "results" : [ "wash_whiskey", "yeast" ]
        }`

These are currently not shown in the itembrowser sadly.

**Comment by DanmakuDan** [comment]
These items have been split into their own "Fermentable" tab in the Consumable list. Their pages also indicate how long it takes to ferment into the next item.
