### ISSUE TITLE
Recursive lists of ingredients not working.

### ISSUE THREAD

**Issue by Soyweiser** [DanmakuDan/cdda-itembrowser#4]
If you look at the 'protein shake' craft page: http://cdda-trunk.chezzo.com/protein_shake/craft you can see that there is a 'sweet_fruit?' item in the list. This is probably because the protein_shake item uses 'sweet_fruit_like' which also includes the 'sweet_fruit' list (the rest of the sweet_fruit_like list does seems to be included).

**Comment by DanmakuDan** [comment]
I wasn't sure what to do with the substitution thing a while ago, but I finally got around to it with f5b13d63139d3d483bdb4c94b12ce491108ccb64. Checking the link in your post should show the fruits substituted properly now.
