### ISSUE TITLE
Clothing/armor stats are different from in-game stats

### ISSUE THREAD

**Issue by Poldraunic-zz** [DanmakuDan/cdda-itembrowser#5]
Good day.

So, I was browsing items and noticed that protection numbers do not add up to the ones in game. Am I misunderstanding it or something is going on there?

**Comment by DanmakuDan** [comment]
The calculations were based on some old code that hadn't been updated in the item browser code, a commit was made to make them match more closely now.

21556a4647c633c91b366b34154de55ac690d100
