### ISSUE TITLE
Searching returns a generic error message

### ISSUE THREAD

**Issue by Kodiologist** [DanmakuDan/cdda-itembrowser#54]
http://cdda-trunk.chezzo.com/search?q=apple yields HTTP 500 with the message "Whoops, looks like something went wrong."

**Comment by Aloxaf** [comment]
So does https://cdda-trunk.chezzo.com/containers .

**Comment by DanmakuDan** [comment]
The search error was due to the web host moving the server contents to a new server (unexpected) and the path to a PHP include was invalid afterwards.

The rest should be working now, will close the issue after seeing that there are no remaining issues with this one.

**Comment by Aloxaf** [comment]
@DanmakuDan Thanks for your work, `/containers` works well now.

But I find another error: https://cdda-trunk.chezzo.com/cs_lajatang_on.

**Comment by DanmakuDan** [comment]
The generic error message might continue for a while, the host doesn't seem to directly support PHP 5.6 from their new CPanel setup (it does still work from editing the .htaccess file), and the code needs to be migrated to the latest framework so that it isn't an issue. In the meantime, the .htaccess file may get reset automatically by the system, so it may break intermittently.

**Comment by Proxiehunter** [comment]
Is the intermittent breakage mentioned in your last post 19 days ago still to be expected or is the "Whoops, looks like something went wrong." message I'm getting whenever I try to search something a sign that something new has gone wrong?

**Comment by DanmakuDan** [comment]
Sorry, been a busy couple of weeks.

Yes, the breakage is still expected, I'm working on updating the webapp to use a newer framework with PHP 7.2. The codebase is using a 5 year old framework for PHP 5.6, and the web host has removed support for old PHP versions on the front-end in the previous month.

**Comment by DanmakuDan** [comment]
The breakage should be fixed now, there were a lot of changes going from Laravel 4.2 to 6.3 and PHP 5.6 to 7.2. Enough stuff has been rearranged that I dropped the update into a new repo at https://github.com/DanmakuDan/cdda-itembrowser-1.1.

**Comment by Kodiologist** [comment]
Why not just start a new branch on the same repo?

**Comment by Kodiologist** [comment]
The site seems to work fine now, by the way. Thanks a ton.

**Comment by DanmakuDan** [comment]
> Why not just start a new branch on the same repo?

I didn't have time earlier to finish rearranging the repo while also having a clean copy to check in, but I think I can work on that now.

**Comment by DanmakuDan** [comment]
I made a few more commits to solve some long-standing errors, and the search function should be in good condition now.
