### ISSUE TITLE
Item qualities carry over to the recipe page containing said item

### ISSUE THREAD

**Issue by Poldraunic-zz** [DanmakuDan/cdda-itembrowser#6]
Somewhat difficult to express the gist of the issue in title. Anyway, for example, [katana](http://cdda-trunk.chezzo.com/katana) can be used to craft naginata and Rising Sun weapons. If you click recipe link you'll see that it lists a lot of different items that aren't crafted from katana. It seems it also lists all craft recipes that are using qualities of an item such as cutting.

I am not sure if this is regression or intended feature. If this is intended feature then I think it should be separate category something like "crafted with" or something along the lines, on the other hand if you want to keep such functionality it should reflected in amount of recipes because on the item page it only lists 2.

**Comment by DanmakuDan** [comment]
The original code had this in as an intended feature, but I think it would make more sense to leave the quality-related items out of the recipe list.

**Comment by DanmakuDan** [comment]
I think we can continue with having the qualities excluded from the craftable recipes list, so this issue will be closed for now.
