### ISSUE TITLE
Certain items are listed in recipes which do not use said item

### ISSUE THREAD

**Issue by Poldraunic-zz** [DanmakuDan/cdda-itembrowser#7]
Another issue which I cannot word relatively shortly. Anyway, item browser says that [firefighter belt](http://cdda-trunk.chezzo.com/fireman_belt) is used as component in one recipe. When you open page with recipes you'll find only "powdered milk" there listed under armor category. 

I am not particularly sure how many items have this issue. After rather quick investigation it seems firefighter belt cannot be disassembled, butchered or used in any crafting recipe. I also checked 0.C item browser and it lists [scavenger gear](http://cdda.chezzo.com/armor_scavenger/craft) which used in its craft. Perhaps issue lies somewhere there?

**Comment by DanmakuDan** [comment]
It looks like the cache had to be cleaned out manually, since a budget steel katana was still listed as crafting everything after the quality linking was removed from the code. There was a 15 MB difference in cached items after the cache was cleaned and rebuilt.

**Comment by DanmakuDan** [comment]
I think the issue was related to the cache, so this will be closed for now.
