### ISSUE TITLE
Page with lifting quality lists no items

### ISSUE THREAD

**Issue by Poldraunic-zz** [DanmakuDan/cdda-itembrowser#8]
Pretty straightforward issue here. No actual in-game item has explicit lifting quality. Perhaps hard code such items for time being? If you do not wish hard code items, perhaps leave links to such items on wiki?

**Comment by DanmakuDan** [comment]
Vehicle parts have been added for now in fb8b091a8b00e8aea9bb8b33d10bec125c05e1ea, ~~but they do not have linking information to the part that they are installed from yet.~~ 75cffacdd70fe2475bdb6bb6f64bb73c1046c40c adds the linking between vehicle part and installed item.

http://cdda-trunk.chezzo.com/crane_medium for reference.
